server:
    port: 18190
spring:
    activemq:
        broker-url: tcp://localhost:61616
#        broker-url: vm://embedded?broker.persistent=false,useShutdownHook=false
        in-memory: true
        non-blocking-redelivery: true
        packages:
            trust-all: false
            trusted: com.net128.sample.activemq1
        pool:
            block-if-full: true
            block-if-full-timeout: -1
            create-connection-on-startup: true
            enabled: false
            expiry-timeout: 0
            idle-timeout: 30000
            max-connections: 1
            maximum-active-session-per-connection: 500
            reconnect-on-exception: true
            time-between-expiration-check: -1
            use-anonymous-producers: true

    # Spring JMS Settings
    jms:
        listener:
            acknowledge-mode: auto
            auto-startup: true
            concurrency: 5
            max-concurrency: 10
        pub-sub-domain: false
        template:
            default-destination:
            delivery-mode: non_persistent
            priority: 100
            qos-enabled: true
            receive-timeout: 1000
            time-to-live: 36000
#  activemq:
#        broker-url: tcp://localhost:61616?jms.redeliveryPolicy.maximumRedeliveries=1
#        password: admin
#        user: admin
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:~/h2/activemq1-msg;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
        driver-class-name: org.h2.Driver
        hikari:
            minimum-idle: 1
            maximum-pool-size: 5
            pool-name: poolname
            maxLifetime: 2000000
            idle-timeout: 10000
            connectionTimeout: 30000
            pool-prepared-statements: true
            max-open-prepared-statements: 250
        username: admin
        password: admin
    h2:
        console:
            enabled: true
            path: /develop/h2_console
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: false
hibernate:
    dialect: org.hibernate.dialect.H2Dialect