FROM openjdk:8-jre-alpine
COPY target/activemq1-0.0.1-SNAPSHOT.jar /usr/local/activemq1.jar
EXPOSE 18190
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=cluster1,jmslistener", "/usr/local/activemq1.jar"]
